name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        build-type: [ Debug, Release ]

    env:
      BUILD_TYPE: ${{ matrix.build-type }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -D${{ matrix.util-assert }}

    - name: Build
      run: cmake --build ${{github.workspace}}/Build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/Build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
